name: Build Resume

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run Docker
        run: |
          docker build -t resume .
          docker run --rm -v ${{ github.workspace }}/CV:/CV resume
